# Generated by Django 4.2.4 on 2023-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_friendrequest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
